export const products = [
  {
    id: 1,
    title: "Grab the best deals",
    image: "./images/grtind.jpg",
    link: "See all upcoming offers",
  },

  {
    id: 2,
    title: "Shop by Category",
    categoryImage1: "./images/Fresh.jpg",
    categoryDescription1: "Fresh",
    categoryImage2: "./images/Mobile.jpg",
    categoryDescription2: "Mobile",
    categoryImage3: "./images/Fashion.jpg",
    categoryDescription3: "Fashion",
    categoryImage4: "./images/Electronic.jpg",
    categoryDescription4: "Electronics",
    link: "New Deals Everyday",
  },

  {
    id: 3,
    title: "Upto 70% Off",
    image: "./images/Clearance.jpg",
    link: "See More Deals",
  },
  {
    id: 4,
    title: "Book Tickets",
    categoryImage1: "./images/Flight.jpg",
    categoryDescription1: "Flight",
    categoryImage2: "./images/Bus.jpg",
    categoryDescription2: "Mobile",
    categoryImage3: "./images/Train.jpg",
    categoryDescription3: "Train",
    categoryImage4: "./images/Travel_accessories.jpg",
    categoryDescription4: "Electronics",
    link: "Hot Ticket Deals",
  },
  {
    id: 5,
    title: "Upgrade Your Home",
    categoryImage1: "./images/TV.jpg",
    categoryDescription1: "Tv",
    categoryImage2: "./images/Fridge.jpg",
    categoryDescription2: "Fridge",
    categoryImage3: "./images/Furniture.jpg",
    categoryDescription3: "Furniture",
    categoryImage4: "./images/Kitchen.jpg",
    categoryDescription4: "Kitchen",
    link: "Your Home Upgrader",
  },
  {
    id: 6,
    title: "Buy and Sell",
    image: "./images/BuySell.jpg",
    link: "Register Now ",
  },
  {
    id: 7,
    title: "Shop Anything Everything",
    categoryImage1: "./images/clothing.jpg",
    categoryDescription1: "Clothes",
    categoryImage2: "./images/watch.jpg",
    categoryDescription2: "Watches",
    categoryImage3: "./images/luggage.jpg",
    categoryDescription3: "Furniture",
    categoryImage4: "./images/Footwear.jpg",
    categoryDescription4: "Aplliances",
    link: "See More Brands",
  },
];
export const yourLists = [
  "Create a Wish List",
  "Wish from Anysite",
  "Baby Wishlistling",
  "Discover Your Style",
  "Explore Showroom",
];
export const yourAccount = [
  "Your Account List",
  "Your Orders Lists",
  "Your Wishlisting",
  "Your Recommendation",
  "Your Membership",
  "Your PrimeVideo",
  "Your SellerAccount",
  "Manage Devices",
];
export const navItems = [
  "Bestsellers",
  "Mobiles",
  "Books",
  "Services",
  "Today's Deals",
  "Electronics",
  "Fashion",
  "Prime",
  "New Releases",
];
export const langOptions = [
  "English-EN",
  "हिन्दी - HI",
  "தமிழ் - TA",
  "తెలుగు - TE",
  "ಕನ್ನಡ - KN",
  " മലയാളം - ML",
  "বাংলা - BN",
  "मराठी - MR",
];
export const deals = [
  {
    id: 1,
    name: "BOAT WATCH",
    image: "./images/boatwatch.jpg",
    off: "upto 75% off",
    dealDay: "Deal of the day",
    MRP: 7999.0,
    discountedPrice: 1999.0,
    delivery: "FREE Delivery",
    description: "Best-Selling Smartwatches - Noise, Boat, Fire-Boltt & more",
    stars: 5,
    reviews: 1333,
  },
  {
    id: 2,
    name: "IQOO MOBILE PHONE",
    image: "./images/Phone.jpg",
    off: "upto 23% off",
    dealDay: "Deal of the day",
    MRP: 20999.0,
    discountedPrice: 16999.0,
    delivery: "FREE Delivery",
    description: "iQOO Z6 5G (Chromatic Blue, 6GB RAM, 128GB Storage)",
    stars: 4.8,
    reviews: 1555,
  },
  {
    id: 3,
    name: "Tetron BUDS",
    image: "./images/buds.jpg",
    off: "upto 80% off",
    dealDay: "Deal of the day",
    MRP: 3999.0,
    delivery: "FREE Delivery",
    discountedPrice: 999.0,
    description: "Offers on Wireless Accessories",
    stars: 3.8,
    reviews: 1777,
  },
  {
    id: 4,
    name: "SKETCHERSHOES",
    image: "./images/Shoe.jpg",
    off: "upto 48% off",
    dealDay: "Deal of the day",
    MRP: 4199.0,
    discountedPrice: 2199.0,
    delivery: "FREE Delivery",
    description: "Skechers Mens Max Protect Sneaker",
    stars: 4.1,
    reviews: 1887,
  },
];
export const productsData = [
  {
    id: 1,
    amount: 1,
    img: "/images/boatwatch.jpg",
    off: "upto 75% off",
    dealDay: "Deal of the day",
    MRP: 7999.0,
    discountedPrice: 1999.0,
    delivery: "FREE Delivery",
    heading:
      "boAt Wave Call Smart Watch, Smart Talk with Advanced Dedicated Bluetooth Calling Chip, 1.69” HD Display with 550 NITS & 70% Color Gamut, 150+ Watch Faces, Multi-Sport Modes,HR,SpO2, IP68(Active Black)",
    stars: 4,
    reviews: 13331,
    links: "Visit the boAt Store",
    item_Price: 1999,
    discount: "-75%",
    mrp: "M.R.P.:₹7,999.00",
    mrp_sub: "Inclusive of all taxes",
    rupee: "₹",
    about: [
      "Bluetooth Calling- Wave Call comes with a premium built-in speaker and bluetooth calling via which you can stay connected to your friends, family, and colleagues",
      "Dial Pad- Its dial pad is super responsive and convenient. You can also save upto 10 contacts in this smart watch",
      "Screen Size- Wave Call comes with a 1.69” HD Display that features a bold, bright, and highly responsive 2.5D curved touch interface",
      "Resolution- With 550 nits of brightness get sharper color resolution that brightens your virtual world exponentially.",
      "Design- The ultra slim and lightweight design of the watch is ideal to keep you surfing your wave all day!",
      "HR, SpO2 & Breathing- Monitor your heart rate and blood oxygen levels on-the-go with the heart rate and SpO2 monitor. It also comes with Guided Breathing to help you relax and embrace mindfulness.",
    ],
  },

  {
    id: 2,
    amount: 1,
    img: "/images/iqooPhone.jpg",
    heading:
      "iQOO Z6 5G (Chromatic Blue, 6GB RAM, 128GB Storage) | Snapdragon 695-6nm Processor | 120Hz FHD+ Display | 5000mAh Battery",
    stars: 4.8,
    reviews: 15555,
    item_Price: 16999,
    links: "Visit the iQOO Store",
    discount: "-23%",
    mrp: "M.R.P.:₹20,999.00",
    mrp_sub: "Inclusive of all taxes",
    rupee: "₹",
    about: [
      "World's First Snapdragon 4 Gen 1 Processor, that allows you to level up your performance.",
      "Best In-Segment 120Hz Screen Refresh Rate: Which comes with lagfree & nimble scrolling.The FHD+ display lets you enjoy to the fullest.",
      "5000mAh Battery: Keeps iQOO Z6 Lite 5G to a longer usage, for a more enjoyable gaming and video experience, which offers Music Playback Time of 127 Hours, Social Media of 21.6 hours, OTT Streaming of 14.5 hours and Gaming of 8.3 hours.",
      "50MP Eye Autofocus main camera, is designed to address the out-of-focus issues. The feature performs fast Eye Autofocus at a high refresh rate.",
      "Stylish & Slim Design: 8.25mm Thin & 194g Weight, with All new 2.5D flat frame design with Matt finish.",
    ],
  },
  {
    id: 3,
    amount: 1,
    img: "/images/miviBuds.jpg",
    off: "upto 75% off",
    dealDay: "Deal of the day",
    MRP: 7999.0,
    discount: "-80%",
    discountedPrice: 1999,
    delivery: "FREE Delivery",
    heading:
      "Mivi DuoPods A350 Earbuds- 50hrs Playtime * *New Launch** True Wireless Earbuds with Rich Bass,13mm Dynamic Drivers, Fast Charging, Made in India, Half in Ear, Metallic Shades, Voice Assistant- Blue",
    stars: 4.5,
    reviews: 13331,
    links: "Visit the Mivi Store",
    item_Price: 1999,
    mrp: "M.R.P.:₹7,999.00",
    mrp_sub: "Inclusive of all taxes",
    rupee: "₹",
    about: [
      "Supreme Bass: The Mivi DuoPods A350 earbuds have supreme Bass audio with All-Powerful 13 mm electro-dynamic bass drivers to make sure you enjoy a jaw-dropping Bass sensation that'll take your breath away",
      "50 Hours of combined Play Hours: These TWS earbuds come with a 500mAh battery to give a combined 50hrs of playtime so that you can jam, chat and binge watch for a whole week on a single charge.",
      "Fantastic Sound Quality: With the Mivi A350 pods, you are treated to truly exceptional, standout audio sound that brings your favourite music or the latest blockbuster movie to life,",
      "Premium Metallic Shades: True Wireless Earbuds Mivi Duopods A350 are available in 5 premium metallic shades you'll immediately fall in love with. Its minimalist matte finish looks like you've never seen anything like it before.",
      "Crystal Clear Calls: These Bluetooth earphones are equipped with two very powerful MEMS microphones for crystal clear calls that help you hear and be heard clearly.",
    ],
  },
  {
    id: 4,
    amount: 1,
    img: "/images/Shoe.jpg",
    off: "upto 75% off",
    dealDay: "Deal of the day",
    MRP: 7999.0,
    discountedPrice: 1999.0,
    delivery: "FREE Delivery",
    heading: "Skechers Mens Max Protect Sneaker",
    stars: 4,
    reviews: 1333,
    links: "Visit the Sketchers Store",
    item_Price: 2199,
    discount: "-75%",
    mrp: "M.R.P.:₹4,199.00",
    mrp_sub: "Inclusive of all taxes",
    rupee: "₹",
    about: [
      "Sole: Rubber",
      "Closure: Lace-Up",
      "Shoe Width: Medium",
      "Goodyear Rubber Mesh Lace-Up Outdoor",
    ],
  },
];
export const personalInfo = [
  "Honey Kalra",
  "#119/c Sector 51 A",
  "Chandigarh",
  "Chandigarh, 160047",
];

export const needHelpPara = [
  "Need help? Check our help pages or contact us",
  "When your order is placed, we'll send you an e-mail message acknowledging receipt of your order. If you choose to pay using an electronic payment method (credit card, debit card or net banking), you will be directed to your bank's website to complete your payment. Your contract to purchase an item will not be complete until we receive your electronic payment and dispatch your item. If you choose to pay using Pay on Delivery (POD), you can pay using cash/card/net banking when you receive your item.",
  "See Amazon.in's Return Policy.",
  "Need to add more items to your order? Continue shopping on the Amazon.in homepage.",
];

export const savedAdress = [
  {
    heading: "Most recently used",
    fullAdress:
      "Honey Kalra #119/C SECTOR 51A, Chandigarh,Chandigarh, 160047, India, Phone number: 94653678833  | ",
    link1: " Edit address",
    link2: "Add delivery instructions",
  },
  {
    heading: "Other addresses",
    fullAdress:
      "Jacob Pahuja Flat no.317 , purvanchal ,royal park society,tower 14, Sector 137, Noida, UTTAR PRADESH, 201305, India, Phone number: 9686388008 |",
    link1: " Edit address",
    link2: "Add delivery instructions",
  },
  {
    fullAdress:
      "Dimple Narula 3865,Mohalla Shukarpura, Rewari, Rewari, HARYANA, 123401, India, Phone number: 9671313080 |",
    link1: " Edit address",
    link2: "Add delivery instructions",
  },
  {
    fullAdress:
      " Dalip Narula Plot no. 157,A, jawahar nagar, Trinity flat no. 304, Sector 4, JAIPUR, RAJASTHAN, 302004, India, Phone number: 8769991964|",
    link1: "Edit address",
    link2: "Add delivery instructions",
  },
  {
    fullAdress:
      "Rajinder Narula Q-1/3,LIC Flat, Sector-6, Vidyadhar Nagar, JAIPUR, RAJASTHAN, 302023, India, Phone number: 9414075865|  ",
    link1: "Edit address",
    link2: "Add delivery instuctions",
  },
];

export const atmCardDetails = [
  {
    id: 0,
    heading: "Pay with Debit/Credit/ATM Cards",
    sub: "You can save your cards as per new RBI guidelines.",
    link: "Learn More",
    img: "/images/payment_methods.png",
  },
  /* {
    id: 1,
    heading: "Net Banking",
    option: [
      "choose any option",
      "Axis Bank",
      "HDFC Bank",
      "ICICI Bank",
      "Kotak Bank",
      "State Bank of India",
      "Allahabad Bank",
      "Andhra Bank",
      "Bank of India",
      "Bank of Maharashtra",
      "Canara Bank",
      "Catholic Syrian Bank",
      "Central Bank of India",
      " City Union Bank",
      "Union Bank of India",
      "United Bank of India",
      "Yes Bank Ltd",
    ],
  },*/
  { id: 1, heading: "Other UPI Apps" },
  {
    id: 2,
    heading: "EMI",
  },
  {
    id: 3,
    heading: "Cash On Delivery/Pay On Delivery",
    sub: "Scan & Pay using Amazon app (₹25 cashback on first transaction). Cash, UPI ,Cards also accepted..",
    link: "Know more",
  },
];
export const customerQ_AnsData = [
  {
    votes: "Votes",
    q: "Question:",
    a: "Answer",
    question: "There is no Water resistant",
    answer: "Yes By Ajay Bajaj on 17 June, 2021",
  },
  {
    votes: "Votes",
    q: "Question:",
    a: "Answer",
    question: "Can I pair two devices at the same time?",
    answer: "Yes u can, it's TWS By Tanmay halder on 29 November, 2021",
  },
  {
    votes: "Votes",
    q: "Question:",
    a: "Answer",
    question: "Battery backup on single charge?",
    answer:
      "If you do not havy use than 7to 10 days battery backup on single full charged By Thounaojam Jolish Luwang on 18 June, 2022",
  },
  {
    votes: "Votes",
    q: "Question:",
    a: "Answer",
    question: "Which charging point c ya other?",
    answer: "Type C By Tanmay halder on 29 November, 2021",
  },
];

export const reviews = [
  {
    name: "Shruti",
    reviewMain: "Good Product",
    reviewDetials: "Reviewed in India on 6 November 2022",
    about: "Colour | BlackSize | ",
    emoji: "🤞👍🏻",
  },
  {
    name: "		Anil Kushwaha",
    reviewMain: "perfect fit",
    reviewDetials: "Reviewed in India on 6 October 2022",
    about: "Colour | LavenderSize | ",
    emoji: "very good",
  },
  {
    name: "	Sandhya sajwan	",
    reviewMain: "Purchase it",
    reviewDetials: "Reviewed in India on 6 October 2022",
    about: "Colour | LavenderSize | ",
    emoji: "Nice product",
  },
  {
    name: "	Suzain",
    reviewMain: "Very nice",
    reviewDetials: "Reviewed in India on 11 November 2022",
    about: "Colour | BlueSize | ",
    emoji: "Good quality product",
  },
];
export const quantity = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "10+"];
export const productCategory = {
  mobilePhone: [
    "CAMERA",
    "SCREENSIZE",
    "SCREETYPE",
    "BATTERY",
    "RAM",
    "SPECIAL FEATURES",
    "MODAL NUMBER",
    "CONNECTIVITY",
    "MANUFACTURER",
  ],
  buds: [
    "BATTERY",
    "SPECIAL FEATURES",
    "MODAL NUMBER",
    "CONNECTIVITY",
    "MANUFACTURER",
  ],
};
export const technicalInformaton = [
  {
    category: "mobilePhone",
    id: 2,
    cameraDescription: "Rear Camera (50MP+2MP+2MP) | 16MP Front Camera",
    screenSize: "6.58 inches",
    screenType: "LCD",
    battery: 5000,
    ram: "6GB",
    processor: "Snapdragon 695 5G",
    operatingSystem: "Funtouch OS 12 Based On Android 12",
    itemWeight: "186 grams",
    gps: true,
    manufacturer: "Vivo",
    specialFeatures: `Fast Charging Support, Fingerprint Sensor, Hybrid Dual SIM, GPS, Video Player, Music Player`,
    connectivity: `USB Type-C, Audio Jack: 3.5mm, Bluetooth, Wi-Fi`,
  },

  {
    id: 3,
    cameraDescription: "Rear Camera (50MP+2MP+2MP) | 16MP Front Camera",
    modelNumber: "TEDPA40-Blue",
    connectivity: `Bluetooth, Wi-Fi`,
    itemWeight: "145 grams",
    gps: true,
    manufacturer: "Mivi",
    specialFeatures: `Sweatproof, Fast Charging, Microphone Included`,
  },
];
